package myrules;

import com.honma.entity.Order;

//100元以下不加分
rule "score_1"
when
    $order:Order(amount<=100)
then
    $order.setScore(0);
    System.out.println("触发了规则：100元以下不加分");
end

rule "score_2"
when
    $order:Order(amount>100&&amount<=500)
then
    $order.setScore(100);
    System.out.println("触发了规则：100-500元加100分");
end

rule "score_3"
when
    $order:Order(amount>500&&amount<=1000)
then
    $order.setScore(500);
    System.out.println("触发了规则：500-1000元加500分");
end

rule "score_4"
when
    $order:Order(amount>1000)
then
    $order.setScore(1000);
    System.out.println("触发了规则：1000元加1000分");
end
